# Generated by Django 5.0.6 on 2024-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_remove_wishlist_url_wishlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='photo',
            field=models.ImageField(default='wishlist/res/default_wishlistpic.png', upload_to='wishlist/res/'),
        ),
    ]
