# Generated by Django 5.0.6 on 2024-08-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_alter_wishlist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
