# Generated by Django 5.0.6 on 2024-08-09 05:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(help_text='Enter a valid hex code, ie #123456 or #ABC', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex code, ie #123456 or #ABC', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('tag_type', models.CharField(choices=[('Preset', 'Preset'), ('Custom', 'Custom')], max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=600)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('total_owed_type', models.CharField(choices=[('Monetary', 'Monetary'), ('Nonmonetary', 'Nonmonetary')], max_length=11)),
                ('total_owed_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('privacy', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=7)),
                ('owner_status', models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Edit', 'Edit'), ('Cancel', 'Cancel'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=16)),
                ('assignee_status', models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Edit', 'Edit'), ('Cancel', 'Cancel'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=16)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_favors', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_favors', to=settings.AUTH_USER_MODEL)),
                ('previous_favor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='favors.favor')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_favors', to='favors.tag')),
            ],
        ),
    ]
