# Generated by Django 4.2.14 on 2024-07-10 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Enter a valid hex code, ie #123456 or #ABC', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex code, ie #123456 or #ABC', regex='^#([a-f0-9]{6}|[a-f0-9]{3})$')]),
        ),
    ]
