# Generated by Django 5.0.7 on 2024-08-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0001_initial'),
        ('wishlist', '0005_alter_wishlist_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favor',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='favor',
            name='assignee_status',
        ),
        migrations.RemoveField(
            model_name='favor',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='favor',
            name='owner_status',
        ),
        migrations.RemoveField(
            model_name='favor',
            name='previous_favor',
        ),
        migrations.AddField(
            model_name='favor',
            name='points_value',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='favor',
            name='total_owed_wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wishlist.wishlist'),
        ),
        migrations.AlterField(
            model_name='favor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='favor',
            name='total_owed_amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
