# Generated by Django 5.0.6 on 2024-08-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0003_favor_bounty_edit_history'),
        ('favors', '0003_favor_points_value'),
    ]

    operations = [
    ]
