# Generated by Django 4.2.14 on 2024-07-11 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0003_tag_created_at_tag_updated_at_alter_favor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='favors',
            field=models.ManyToManyField(to='favors.favor'),
        ),
        migrations.AlterField(
            model_name='favor',
            name='tags',
            field=models.ManyToManyField(blank=True, to='favors.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Enter a valid hex code, ie #123456 or #ABC', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex code, ie #123456 or #ABC', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
