# Generated by Django 5.0.7 on 2024-08-14 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0003_favor_points_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='favor',
            name='total_owed_amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='favor',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
