# Generated by Django 5.0.7 on 2024-08-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0003_favor_points_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='emoji',
            field=models.CharField(default='', max_length=1),
        ),
    ]
