# Generated by Django 5.0.7 on 2024-08-14 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0004_alter_favor_created_at_alter_favor_total_owed_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
