# Generated by Django 4.2.14 on 2024-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0006_remove_tag_favor_tag_favors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='favors',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='favors.favor'),
        ),
    ]
