# Generated by Django 5.0.7 on 2024-08-14 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0006_alter_favor_created_at_alter_favor_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
