# Generated by Django 4.2.14 on 2024-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0007_alter_tag_favors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='status',
            field=models.CharField(choices=[('Pending creation', 'Pending'), ('Pending edits', 'Pending edits'), ('Pending deletion', 'Pending deletion'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete')], max_length=16),
        ),
    ]
