# Generated by Django 5.0.7 on 2024-08-14 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0007_alter_favor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2024, 8, 14)),
        ),
    ]
