# Generated by Django 5.0.7 on 2024-08-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0004_tag_emoji'),
        ('favors', '0008_alter_favor_created_at'),
    ]

    operations = [
    ]
