# Generated by Django 5.0.7 on 2024-08-20 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0009_merge_0004_tag_emoji_0008_alter_favor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2024, 8, 20)),
        ),
    ]
