# Generated by Django 4.2.14 on 2024-07-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0009_alter_favor_status_alter_tag_favors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='favors',
        ),
        migrations.AddField(
            model_name='favor',
            name='tags',
            field=models.ManyToManyField(to='favors.tag'),
        ),
    ]
