# Generated by Django 5.0.6 on 2024-08-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0004_merge_20240814_1645'),
        ('favors', '0009_merge_0004_tag_emoji_0008_alter_favor_created_at'),
    ]

    operations = [
    ]
