# Generated by Django 4.2.14 on 2024-07-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0010_remove_tag_favors_favor_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='tags',
            field=models.ManyToManyField(blank=True, to='favors.tag'),
        ),
    ]
