# Generated by Django 5.0.6 on 2024-08-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0010_alter_favor_created_at'),
        ('favors', '0010_merge_20240820_2113'),
    ]

    operations = [
    ]
