# Generated by Django 5.0.7 on 2024-08-21 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0011_merge_20240821_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2024, 8, 21)),
        ),
    ]
