# Generated by Django 5.0.7 on 2024-08-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0012_alter_favor_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favor',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='favor',
            name='bounty_edit_history',
        ),
        migrations.AddField(
            model_name='favor',
            name='button_states',
            field=models.JSONField(default={'assignee': {'CANCEL': True, 'COMPLETE': False, 'CREATE': True, 'DELETE': False, 'EDIT': False}, 'owner': {'CANCEL': True, 'COMPLETE': False, 'CREATE': False, 'DELETE': False, 'EDIT': False}}),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
