# Generated by Django 4.2.14 on 2024-07-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0012_tag_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='status',
            field=models.CharField(choices=[('Pending_creation', 'Pending_creation'), ('Pending_edits', 'Pending_edits'), ('Pending_deletion', 'Pending_deletion'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete')], max_length=16),
        ),
    ]
