# Generated by Django 5.0.6 on 2024-08-22 20:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0013_remove_favor_tags_remove_favor_bounty_edit_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
