# Generated by Django 5.0.6 on 2024-08-22 20:45

import favors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0014_alter_favor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='button_states',
            field=models.JSONField(default=favors.models.get_default_button_states),
        ),
    ]
