# Generated by Django 4.2.14 on 2024-07-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0015_alter_favor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_favors', to='favors.tag'),
        ),
    ]
