# Generated by Django 4.2.14 on 2024-07-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0016_alter_favor_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='status',
            field=models.CharField(choices=[('Pending_creation', 'Pending_creation'), ('Pending_edits', 'Pending_edits'), ('Pending_deletion', 'Pending_deletion'), ('Incomplete', 'Incomplete'), ('Complete', 'Complete')], max_length=16),
        ),
    ]
