# Generated by Django 5.0.7 on 2024-07-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0017_alter_favor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favor',
            name='status',
        ),
        migrations.AddField(
            model_name='favor',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favor',
            name='assignee_status',
            field=models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Edit', 'Edit'), ('Cancel', 'Cancel'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='None', max_length=16),
        ),
        migrations.AddField(
            model_name='favor',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favor',
            name='owner_status',
            field=models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Edit', 'Edit'), ('Cancel', 'Cancel'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='None', max_length=16),
        ),
    ]
