# Generated by Django 5.0.7 on 2024-07-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0018_remove_favor_status_favor_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='assignee_status',
            field=models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Edit', 'Edit'), ('Cancel', 'Cancel'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('None', 'None')], default='None', max_length=16),
        ),
        migrations.AlterField(
            model_name='favor',
            name='owner_status',
            field=models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Edit', 'Edit'), ('Cancel', 'Cancel'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('None', 'None')], default='None', max_length=16),
        ),
    ]
