# Generated by Django 5.0.7 on 2024-07-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0019_alter_favor_assignee_status_alter_favor_owner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='assignee_status',
            field=models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Edit', 'Edit'), ('Cancel', 'Cancel'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=16),
        ),
        migrations.AlterField(
            model_name='favor',
            name='owner_status',
            field=models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Edit', 'Edit'), ('Cancel', 'Cancel'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=16),
        ),
    ]
