# Generated by Django 5.0.6 on 2024-08-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
