# Generated by Django 5.0.6 on 2024-08-09 19:58

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='code',
            field=models.CharField(blank=True, default=users.models.create_new_ref_number, editable=False, max_length=10, unique=True),
        ),
    ]
