# Generated by Django 5.0.7 on 2024-08-10 20:43

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofileinfo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='code',
            field=models.CharField(blank=True, default=users.models.create_new_ref_number, max_length=10, unique=True),
        ),
    ]
