# Generated by Django 5.0.7 on 2024-07-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_linkedaccounts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_image',
            field=models.ImageField(upload_to='res/'),
        ),
    ]
