# Generated by Django 5.0.7 on 2024-07-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_linkedaccounts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='friend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='pubpriv_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='rating_score',
            field=models.IntegerField(default=0),
        ),
    ]
