# Generated by Django 5.0.6 on 2024-08-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofileinfo_display_name'),
        ('users', '0002_userprofileinfo_favoritedfriends'),
    ]

    operations = [
    ]
