# Generated by Django 5.0.6 on 2024-07-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofileinfo_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='friend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='rating_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
