# Generated by Django 5.0.7 on 2024-08-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofileinfo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccounts',
            name='provider_text',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
