# Generated by Django 5.0.6 on 2024-07-24 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofileinfo_profile_image'),
        ('users', '0003_userprofileinfo_friend_count_and_more'),
    ]

    operations = [
    ]
