# Generated by Django 5.0.7 on 2024-08-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_linkedaccounts_provider_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_image',
            field=models.ImageField(default='users/res/default_pfp.png', upload_to='users/res/'),
        ),
    ]
